=head1 Extopus - The Monitoring Aggregator

Over the years, many monitoring applications have been developed in
OpenSource space. MRTG, Nagios, Cacti, Ganglia, Torrus, OpenNMS, Munin or
collectd to name only a few. Each of them comes with its own web interface.
Most of these web interfaces have been developed several years ago and do
not make much use of today's Web technologies.

Deploying a large scale monitoring system is a major effort. Especially when
it is to be integrated with other parts of the infrastructure. This makes it
quite difficult to move from one monitoring product to another.

Often several different monitoring systems are running in parallel to cater
for all the monitoring needs. Sometimes even observing the same properties
for different internal needs (Networkadministartion, Customer portal).

The user experience is often not ideal, up to the point where proprietary
solutions are being considered due to the superior looks of their web
interfaces and marketing literature.

Extopus is an aggregating front end to a wide array of monitoring systems.
Its plug-in system provides an easy route to integrating data from several
systems into a single instance of Extopus.

If connected to an authentication and authorization provider, Extopus can
also present only a subset of the information available for integration into
customer portals and other limited access scenarious.

See the the documentation for for more information.
