=head1 Mongregator - The Monitoring Aggregator

Over the years, many monitoring applications have been developed in
OpenSource space. MRTG, Nagios, Cacti, Ganglia, Torrus, OpenNMS, Munin or
collectd to name only a few. Each of them comes with its own web interface.
Most of these web interfaces have been developed several years ago and do
not make much use of today's Web technologies.

Deploying a monitoring system within a whole organization is quite an
effort. Especially when it is to be integrated other parts of the
infrastructure. This makes it quite difficult to from one monitoring product
to another.

Two scenarios seem to be prevail. Several different monitoring systems are
running in parallel or the local monitoring system is a heavily customized
version of some open source system.  In both cases, the user experience is
often not ideal, up to the point where proprietary solutions are being
considered due to the superior looks of their web interfaces and marketing
literature.

Mongregator is an aggregating front end to a wide array of monitoring
systems. Its plug-in system provides an easy route to integrating several
systems into a single instance of Mongragator. Mongregator is very flexible.
It provides integration abilities from direct RRD access iframe view of
web pages.

See the the documentation for for more information.
