=head1 Extopus Architectural Overview

=head2 Concept

Extopus is an aggregating front end to a wide array of monitoring
systems. Extopus uses a modular architecture which allows for simple
integration with other system.

RRDtool has become a kind of common storage and presentation system for many
monitoring systems. Extopus has therefore rich support for rrdtool based
data stores.

Accessing a monitoring system from Extopus can be as superficial as
directly including a web page into a Extopus iframe or it can be as deep
as giving extopus direct access to the rrd files or pulling  in tabular data.

There are three strategies for integrating an existing tool with Extopus:

=over

=item *

Write a L<tool specific plugin|/"Plugin API"> for Mongragator and use
whatever methods for interaction the tool already supports.

=item *

Add a JSON RPC interface to your monitoring system for
Extopus to access directly using the Extopus L<native
plugin|/"Native Extopus Integration">.

=item *

Teach your Monitoring System to send its information to Extopus via the
L<Extopus JSON RPC Interface|/"Extopus JSON RPC">.

=back

=head2 Data Model

Extopus views the world as a collection of information nodes. Each node
has a number of properties. The properties are split into three namespaces:
required, optional and informational. A node must provide at least the
required properties. Extopus will use information from optional
properties to improve the user experience. Informational properties can
contain any extra data you wish to display along with the node properties.

Extopus can show the nodes it knows as a list or as a tree. The tree
view uses property values to build the tree. For performance reasons
Extopus creates a persistant node cache which gets updated as new
information becomes available.

=head2 Integration

=head3 Native Extopus Integration

For native integration, a system has to support a set of JSON-RPC calls.
They are centered around pulling in information about the available nodes
and details about the data associated with a particular node.

=head3 Plugin API

Instead of adding Extopus support to a particular tool it is also
possible to teach Extopus how to talk to a tools existing interfaces.
This is done by creating a tool specific plugin for Extopus.

=head3 Extopus JSON RPC

Monitoring Applications can push their information to Extopus via a JSON
RPC Webservice.

=head2 Virtual Nodes

Based on the information Extopus has imported it can build virtual
nodes, presenting information created by combining information from multiple
sources. Virtual nodes are generated by plugins, accessing the extopus
data store.

=head2 Data Export and Printing

Extopus provides several predefined widgets which can be combined into
screens for information presentation. Depending on the widgets used in a
screen, the content of the widget or the whole screen can be downloaded
as pdf or csv.

Users can configure report screens to be sent to their email account at
regular intervals.

=head2 Access Control

Access Control is based on node filtering. Each user or group of users can
be linked with filtering experssions restricting the nodes they can view.

By using virutal nodes in connection with access control, it is possible to
restrict users to high level views.

=head2 Dashboard

Users can drag and drop widgets from individual node screens into a
dashboard screens, assembling their personal control center.

